describe("MentalBreakdown Film Production Suite E2E Flow", () => {
  beforeEach(() => {
    // Clear localStorage to start with a clean state
    cy.clearLocalStorage();
    cy.visit("/");
  });

  it("should load the dashboard and verify initial state", () => {
    cy.contains("MentalBreakdown").should("exist");
    cy.contains("New Project").should("exist");
  });

  it("should create a new project and open it in Schedule Editor", () => {
    // Click New Project
    cy.contains("New Project").click();

    // Fill project name in modal
    cy.get('input[placeholder="e.g. Short Film 2026"]')
      .should("be.visible")
      .type("Cypress Testing Film");

    // Enter project description
    cy.get('textarea[placeholder="Brief description of your project..."]')
      .type("This is a test project generated by Cypress E2E.");

    // Submit form
    cy.contains("button", "Create Project").click();

    // Wait for "Open Project" selection modal
    cy.contains("Choose how to open").should("be.visible");

    // Click "Schedule" to open in schedule editor
    cy.get(".option-card.schedule").click();

    // Verify Schedule Editor view is rendered
    cy.contains("Shooting Schedule Editor").should("be.visible");
    cy.contains("Add Shot").should("be.visible");
    cy.contains("Add Break").should("be.visible");

    // Add a shot row to the schedule
    cy.contains("Add Shot").click();

    // Switch to Shot View to make the shot number input visible
    cy.contains("Shot View").click();

    // Find the shot row inputs and edit them
    cy.get('input[placeholder="1A"]').last().should("be.visible").type("1A").blur();
    cy.get('input[placeholder="001"]').last().should("be.visible").type("001").blur();

    // Add a break row to the schedule
    cy.contains("Add Break").click();
    cy.get('input[placeholder="Break description"]')
      .last()
      .clear({ force: true })
      .type("Lunch Break", { force: true })
      .blur();

    // Wait for the autosave debounce and flush to complete
    cy.wait(2000);

    // Return to dashboard
    cy.get("svg.lucide-arrow-left").parent().click();

    // Verify the project card is saved and visible on the dashboard
    cy.contains("Cypress Testing Film").should("be.visible");
    // Verify the project card badge for having schedule data
    cy.contains("Schedule").should("be.visible");
  });
});
